services:
  app-automacao:
    build: .
    container_name: streamlit_automacao_contratos
    ports:
      - "8503:8501"
    
    # 1. INJETA AS VARIÁVEIS DE AMBIENTE DIRETAMENTE DO ARQUIVO
    env_file:
      - .env 
      
    # 2. FORÇA O HOT-RELOAD DO STREAMLIT DENTRO DO DOCKER
    environment:
      - STREAMLIT_SERVER_RUN_ON_SAVE=true
      - STREAMLIT_SERVER_FILE_WATCHER_TYPE=poll
    
    # 3. GARANTE QUE O CONTÊINER CONSIGA ENXERGAR O BANCO LOCAL (CASO NECESSÁRIO)
    extra_hosts:
      - "host.docker.internal:host-gateway"
    
    # 4. ESPELHA O CÓDIGO (PERMITE ATUALIZAR O APP SEM REFAZER O BUILD)
    volumes:
      - .:/app
      
    restart: unless-stopped